### ISSUE TITLE
pygit2 LFSFilter not working

### ISSUE THREAD

**Issue by leiless** [iterative/scmrepo#363]
Hi, I have a simple python project which depends on

```
pygit2==1.15.0
scmrepo==3.3.5
```

```python
import pygit2
import scmrepo.git.backend.pygit2.filter

# The default priority is GIT_FILTER_DRIVER_PRIORITY=200
# https://github.com/libgit2/libgit2/blob/main/include/git2/sys/filter.h#L42-L47
pygit2.filter_register('lfs', scmrepo.git.backend.pygit2.filter.LFSFilter)

# Do the pygit2 clone job
# repo_url = '...' # This is a repository with LFS
# repo_dir = '...'
# repo = pygit2.clone_repository(repo_url, repo_dir)
```

But after I cloned the git repo, I found those git LFS files are still plain git LFS object text files.
Just like:

```
version https://git-lfs.github.com/spec/v1
oid sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
size 119954
```

It indicates that the git LFS filters are not working or effective, does anyone can help with this?
cc @pmrowla

FYI, the git repo is a private git repository from github.com, cloned using the ssh protocol.

**Comment by skshetry** [comment]
AFAIK, you have to call [`fetch()`](https://github.com/iterative/scmrepo/blob/f9bb897ba5b9aff8aa5bd480c72f7d1cef0561b1/src/scmrepo/git/lfs/fetch.py#L18) yourself. 

https://github.com/iterative/scmrepo/blob/f9bb897ba5b9aff8aa5bd480c72f7d1cef0561b1/src/scmrepo/git/lfs/fetch.py#L18


Also, note that the scmrepo is a lower-level library for dvc. The purpose of this library was to abstract different git implementations so that we can use different features that are not implemented in one library vs other (and, improve performance). 

We do not support the use of internals, however you may use at your own risk.

**Comment by pmrowla** [comment]
The LFS filter only implements the low level LFS smudge behavior. It is not a complete LFS client, and does not add anything to the pygit2/libgit2 clone/fetch/pull behavior. The pygit2 LFS filter will only work as expected when the required LFS objects are available in LFS storage (meaning they need to be explicitly fetched before doing a pygit2/libgit2 checkout). You are not seeing the LFS files in your cloned repo because the LFS objects have not been fetched into LFS storage.

If you are trying to use pygit2 directly (without anything else from scmrepo) you can re-use this LFS filter for handling the smudge behavior upon libgit2 checkout or when reading from the ODB. However, you will still need to implement the LFS client + fetch logic yourself.

---

scmrepo includes parts of what you are looking for, but as @skshetry noted, scmrepo is mainly intended to be used in DVC. As a result, the LFS client behavior for modifying your working directory is mostly not implemented here (since DVC reads directly from the git index when dealing with LFS files and does not care about the working directory at all). You can approximate what you are looking for with scmrepo and pygit2, but it will be somewhat convoluted for these reasons.

I think something along these lines would work, but this is not tested and you will probably need to tweak things

```py
from scmrepo.git import git
from scmrepo.git.lfs import fetch as lfs_fetch

# clone the repo
scm = Git.clone(repo_url, repo_dir)

# fetch LFS objects for HEAD (and only HEAD), if you need LFS objects for other commits
# you need to explicitly fetch them (see the docstrings for `scmrepo.git.lfs.fetch`)
lfs_fetch(scm)

# remove old checkout of LFS pointer files, you will need to do this for all of your LFS files
os.remove("some_file")

# re-run pygit2 checkout to use the correct fetched LFS objects instead of pointer files
#
# note that scm.checkout() is insufficient here because it may opt for using a non-pygit2
# git backend
scm.pygit2.repo.checkout("HEAD")
```
