### ISSUE TITLE
Dulwich fails when there's no GCC

### ISSUE THREAD

**Issue by IWillPull** [iterative/scmrepo#73]
Basically, this issue is back again in DVC: https://github.com/iterative/dvc/issues/2010

**Comment by efiop** [comment]
Looks like dulwich broke wheel build again 🙁 https://github.com/jelmer/dulwich/issues/968 Thanks @dtrifiro for a quick fix.

Looks like we need to set an upper bound on dulwich in scmrepo for now and think about how we can help dulwich releases not break so often.

**Comment by dtrifiro** [comment]
Fix has been merged https://github.com/jelmer/dulwich/pull/969

**Comment by efiop** [comment]
For the record:

let's put an upper bound on dulwich and make sure when we test scmrepo we install using --bin-only(or whatever that pip flag is called) to make sure that all wheels are available. That will also help us catch such problems during dependabot's PRs for bumbing dulwich version.

**Comment by skshetry** [comment]
I am against putting any upper bound. This is a packaging issue, and these mistakes/bugs happen, which will automatically get fixed with time.

Pinning the dependencies will make it painful for users if other packages also depend in dulwich.
It is also going to be painful for us, since DVC pins scmrepo, so to bump version, we need to also make a release in DVC.
